### ISSUE TITLE
conda-lock conda distribution fails to install necessary dependencies to solve environment files with pip dependencies

### ISSUE THREAD

**Issue by matthewfeickert** [conda/conda-lock#265]
Hi. It seems that the Conda distribution of `conda-lock` `v1.2.1` fails to install necessary dependencies (the [deprecated `lockfile` library](https://pypi.org/project/lockfile/)) for solving environments that contain `pip` dependencies.

Here's a minimal failing example environment and Dockerfile:

## Minimal Failing Example

* `environment.yml`
```yaml
name: base
channels:
  - conda-forge
dependencies:
  - python==3.8.*
  - awkward==1.10.1
  - pip>=22.3
  - pip:
    - fastjet==3.3.4.0rc9
```

* `Dockerfile`
```dockerfile
FROM condaforge/mambaforge:4.14.0-0 as builder

COPY environment.yml /docker/environment.yml

RUN . /opt/conda/etc/profile.d/conda.sh && \
    mamba create --name lock && \
    conda activate lock && \
    mamba env list && \
    mamba install --yes 'conda-lock==1.2.1' && \
    conda-lock lock \
        --platform linux-64 \
        --file /docker/environment.yml \
        --kind lock \
        --lockfile /docker/conda-lock.yml
```

```console
$ docker pull condaforge/mambaforge:4.14.0-0
$ docker build --file Dockerfile --tag conda-lock/debug:issue-265 .
...
Locking dependencies for ['linux-64']...
INFO:conda_lock.conda_solver:linux-64 using specs ['python 3.8.*', 'awkward 1.10.1', 'pip *']
Traceback (most recent call last):
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/cachecontrol/caches/file_cache.py", line 77, in __init__
    from lockfile import LockFile
ModuleNotFoundError: No module named 'lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/lock/bin/conda-lock", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 1190, in lock
    lock_func(
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 949, in run_lock
    make_lock_files(
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 389, in make_lock_files
    lock_content = lock_content | create_lockfile_from_spec(
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 737, in create_lockfile_from_spec
    deps = _solve_for_arch(
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 703, in _solve_for_arch
    pip_deps = solve_pypi(
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/conda_lock/pypi_solver.py", line 215, in solve_pypi
    pypi = PyPiRepository()
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/conda_lock/_vendor/poetry/repositories/pypi_repository.py", line 72, in __init__
    self._cache_control_cache = FileCache(str(release_cache_dir / "_http"))
  File "/opt/conda/envs/lock/lib/python3.10/site-packages/cachecontrol/caches/file_cache.py", line 87, in __init__
    raise ImportError(notice)
ImportError: 
NOTE: In order to use the FileCache you must have
lockfile installed. You can install it via pip:
  pip install lockfile

```

Here's the full log attached: [fail.log](https://github.com/conda-incubator/conda-lock/files/9873671/fail.log)

```
docker build --file Dockerfile --tag conda-lock/debug:issue-265 . &> fail.log
```

## Minimal Working Example with `pip`

Note that this is a Conda distribution issue only. If you install `conda-lock` from PyPI then things succeed:

```dockerfile
FROM condaforge/mambaforge:4.14.0-0 as builder

COPY environment.yml /docker/environment.yml

RUN . /opt/conda/etc/profile.d/conda.sh && \
    mamba create --name lock && \
    conda activate lock && \
    mamba env list && \
    mamba install --yes pip && \
    echo "conda-lock fails to lock if installed with mamba" && \
    python -m pip install --upgrade pip setuptools wheel && \
    python -m pip install 'conda-lock==1.2.1' && \
    conda-lock lock \
        --platform linux-64 \
        --file /docker/environment.yml \
        --kind lock \
        --lockfile /docker/conda-lock.yml
```

```console
$ docker run --rm conda-lock/debug:issue-265 /bin/bash -c 'ls -lhtra /docker'
total 28K
-rw-rw-r-- 1 root root  138 Oct 26 20:44 environment.yml
-rw-r--r-- 1 root root  16K Oct 26 20:54 conda-lock.yml
drwxr-xr-x 1 root root 4.0K Oct 26 20:54 .
drwxr-xr-x 1 root root 4.0K Oct 26 20:55 ..
```

**Comment by mariusvniekerk** [comment]
Should be fixed once https://github.com/conda-forge/conda-lock-feedstock/pull/36 propagates

**Comment by matthewfeickert** [comment]
Thanks!

**Comment by matthewfeickert** [comment]
Thanks very much @mariusvniekerk. With that patch to the conda-forge feedstock my original minimal failing example now works. :+1:

**Comment by Cakell** [comment]
Hi.

I'm having the exact same issue, even with `conda-lock` `v1.4.0`.

I don't use a docker file, simply ran the following command in bash:

```bash
conda-lock -f environment.yml -p linux-64 -p win-64
```

## Minimal Failing Example

* `environment.yml`
```
name: base
channels:
  - conda-forge
dependencies:
  - python==3.9
  - pip>=22.3
  - pip:
    - fastjet==3.3.4.0rc9
```

```bash
$ conda-lock -f env2.yml -p linux-64 -p win-64
Locking dependencies for ['linux-64', 'win-64']...
INFO:conda_lock.conda_solver:linux-64 using specs ['python 3.9', 'pip *']
 Traceback (most recent call last):
  File "C:\miniconda3\lib\site-packages\cachecontrol\caches\file_cache.py", line 77, in __init__
    from lockfile import LockFile
ModuleNotFoundError: No module named 'lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\miniconda3\Scripts\conda-lock-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\miniconda3\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\miniconda3\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\miniconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\miniconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\miniconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\miniconda3\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 1353, in lock
    lock_func(
  File "C:\miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 1083, in run_lock
    make_lock_files(
  File "C:\miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 408, in make_lock_files
    lock_content = lock_content | create_lockfile_from_spec(
  File "C:\miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 801, in create_lockfile_from_spec
    deps = _solve_for_arch(
  File "C:\miniconda3\lib\site-packages\conda_lock\conda_lock.py", line 737, in _solve_for_arch
    pip_deps = solve_pypi(
  File "C:\miniconda3\lib\site-packages\conda_lock\pypi_solver.py", line 222, in solve_pypi
    pypi = PyPiRepository()
  File "C:\miniconda3\lib\site-packages\conda_lock\_vendor\poetry\repositories\pypi_repository.py", line 72, in __init__
    self._cache_control_cache = FileCache(str(release_cache_dir / "_http"))
  File "C:\miniconda3\lib\site-packages\cachecontrol\caches\file_cache.py", line 87, in __init__
    raise ImportError(notice)
ImportError:
NOTE: In order to use the FileCache you must have
lockfile installed. You can install it via pip:
  pip install lockfile
```

I don't really understand how the optional dep for cachecontrol `filelock >=3.8.0` should change the code's behavior from trying the import the [deprecated lockfile library](https://pypi.org/project/lockfile/).

Thanks in advance!

**Comment by Cakell** [comment]
Thanks @maresb.

I see that `cachecontrol` `0.12.12` has been yanked almost 2 months ago ([conda-forge/cachecontrol-feedstock#15](https://github.com/conda-forge/cachecontrol-feedstock/issues/15)), so if I understand correctly - it can't be used to fix the above problem (or at all).

Does you know if anyone is working on a fix?

**Comment by maresb** [comment]
I hope that https://github.com/conda-forge/conda-lock-feedstock/pull/40 fixes it. We should probably add a test since we're missing coverage of this case.

**Comment by Cakell** [comment]
Fixed!!

Thank you very much for your quick response and delivery! @maresb @bollwyvl

**Comment by Cakell** [comment]
As far as I know, this issue can be closed again. Thanks again for the help!
