### ISSUE TITLE
KeyError: 'pkgs_dirs'

### ISSUE THREAD

**Issue by valeriupredoi** [conda/conda-lock#732]
Hi @maresb Ben, we're seeing this failure at creating a linux64 conda lock file:

- conda-lock 2.5.7 build `pyhd8ed1ab_0       conda-forge`
- click 8.1.7 build `unix_pyh707e725_0  conda-forge`
- invocation: `conda-lock lock --platform linux-64 -f environment.yml --mamba --kind explicit`
- see the actual fail at https://github.com/ESMValGroup/ESMValTool/actions/runs/11286190143/job/31498329250
- trace:

```
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/bin/conda-lock", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/conda_lock/conda_lock.py", line 1403, in lock
    lock_func(
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/conda_lock/conda_lock.py", line 1111, in run_lock
    make_lock_files(
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/conda_lock/conda_lock.py", line 393, in make_lock_files
    fresh_lock_content = create_lockfile_from_spec(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/conda_lock/conda_lock.py", line 836, in create_lockfile_from_spec
    deps = _solve_for_arch(
           ^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/conda_lock/conda_lock.py", line 748, in _solve_for_arch
    conda_deps = solve_conda(
                 ^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/conda_lock/conda_solver.py", line 159, in solve_conda
    dry_run_install = solve_specs_for_arch(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/conda_lock/conda_solver.py", line 383, in solve_specs_for_arch
    return _reconstruct_fetch_actions(conda, platform, dryrun_install)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/conda_lock/conda_solver.py", line 277, in _reconstruct_fetch_actions
    for d in json.loads(
             ^^^^^^^^^^^
KeyError: 'pkgs_dirs'
```

Unfortunately I can't reproduce this on my local machine (ie all works fine, with same dependencies), but it is 100% reproducible on the Github Actions machine. Any clues? Many thanks in advance! 🍻

**Comment by maresb** [comment]
Hey there @valeriupredoi! Working on an OSS project with a visible workflow makes this a whole lot easier than usual to diagonse! 😁 

I'd recommend adding a workflow dispatch trigger to give you the following button:

![Image](https://github.com/user-attachments/assets/15e281dd-1ba4-4270-a4ca-03121f201814)

I think this is probably due to Micromamba v2. Experiment in progress at
https://github.com/ESMValGroup/ESMValTool/pull/3773

**Comment by valeriupredoi** [comment]
ah interesting, cheers, Ben! Will go there now 🍺

**Comment by maresb** [comment]
It was indeed v2: https://github.com/ESMValGroup/ESMValTool/pull/3771

I'm a bit concerned about the KeyError reported above. This needs more investigation.

**Comment by maresb** [comment]
Thanks so much @valeriupredoi for the bug report! It turns out it was an obscure bug in conda-lock, triggered from a side-effect of the upgrade. In this case mamba v2 was not at fault. Once I release conda-lock v3 you can unpin mamba.

**Comment by valeriupredoi** [comment]
excellent @maresb - glad I could help, and well done for figuring out what the actual problem was! Many thanks, I will make a note for us, so we unpin mamba as soon as v3 comes out. Also, close this then? 🍺

**Comment by valeriupredoi** [comment]
ah nvmd, just saw #733 is still open 👍

**Comment by ctcjab** [comment]
Just hit this bug. Great to see it's fixed on the main branch. Is a workaround available while the fix has not yet made it into a stable release?

**Comment by maresb** [comment]
Check https://github.com/conda/conda-lock/issues/725 for recommended install instructions from `main`.

Will soon reach out privately as well.

**Comment by ctcjab** [comment]
> Check https://github.com/conda/conda-lock/issues/725 for recommended install instructions from main.

Is there a lower-risk workaround that doesn't require installing an unreleased version of conda-lock that includes breaking changes, such as merely setting some environment variable, or passing some additional flag to CLI invocations?

In case it's a clue, we started observing this once we upgraded conda from v24 to v25.1.0 (latest stable release, to pick up the fix for https://github.com/conda/conda/issues/13488). If you think that's the culprit and that downgrading conda back to v24 is the best workaround, I'd rather take the *.partial download bug over this bug in conda-lock, but please let me know if there's a better alternative.

> Will soon reach out privately as well.

Great, thank you, looking forward to hearing from you!

**Comment by valeriupredoi** [comment]
brilliant, very many thanks @maresb - my apologies it took me a fair while to thank you 😁 🍻
